development:
  adapter: sqlite3
  database: db/china.devel.sqlite3
  timeout: 5000
test:
  adapter: sqlite3
  database: db/china.sqlite3
  timeout: 5000
production:
  adapter: sqlite3
  database: db/china.sqlite3
  timeout: 5000